/home/Talen/miniconda3/envs/cv4ecology2/lib/python3.9/site-packages/torchvision/transforms/v2/_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(
/home/Talen/miniconda3/envs/cv4ecology2/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/Talen/miniconda3/envs/cv4ecology2/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Epoch 1/100
[Train] Loss: 0.38; OA: 92.33%; class 1 label count: 496.00 ; class 1 correct pred count: 333.00; class 0 label count: 148676.00; class 0 correct pred count: 1373
############
class 1 accuracy: tensor(0.6714, device='cuda:0')
class 0 accuracy: tensor(0.9241, device='cuda:0')
  0%|                                                                                                                                     | 0/167 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/Talen/foragefish_classifier/ct_classifier/train.py", line 396, in <module>
    main()
  File "/home/Talen/foragefish_classifier/ct_classifier/train.py", line 366, in main
    loss_val, oa_val = validate(cfg, dl_val, model) #todo put back MAH
  File "/home/Talen/foragefish_classifier/ct_classifier/train.py", line 258, in validate
    for idx, (data, labels) in enumerate(dataLoader):
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/Talen/foragefish_classifier/ct_classifier/train.py", line 396, in <module>
    main()
  File "/home/Talen/foragefish_classifier/ct_classifier/train.py", line 366, in main
    loss_val, oa_val = validate(cfg, dl_val, model) #todo put back MAH
  File "/home/Talen/foragefish_classifier/ct_classifier/train.py", line 258, in validate
    for idx, (data, labels) in enumerate(dataLoader):
ValueError: too many values to unpack (expected 2)
